### ISSUE TITLE
[sketch] Causa e Efeito

### ISSUE THREAD

**Issue by SwampTG** [UnBArqDsw2022-1/2022_1_grupo5#14]
### Summary

Diagrama que reúne os aspectos levantados pelo grupo e tenta analisar novas causas para efeitos desejados ou indesejados, do produto ou do projeto

### Motivation

Documento facilitador da visualização dos problemas e soluções. Artefato de entrega necessária para a disciplina.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SwampTG** [comment]
## Diagramas:

![Cause_And_Effect_USER](https://user-images.githubusercontent.com/66492055/175382804-e9cb866d-5dfe-4580-bb2a-b58945e034be.png)
![Cause_And_Effect+_PROJ](https://user-images.githubusercontent.com/66492055/175382813-32ce6dcd-8e18-4041-ac30-83e3c918567c.png)
![Cause_And_Effect_PROFISS](https://user-images.githubusercontent.com/66492055/175382814-d04010d9-fa7d-412b-b9e7-12db8683d9bd.png)
![Cause_And_Effect_BAD_PRODUCT](https://user-images.githubusercontent.com/66492055/175382815-41f841e4-9263-44f6-81d5-0677ab26b633.png)

**Comment by SwampTG** [comment]
@DanielViniciusAlves Dá uma olhada, que não consegui dar push no artefato ainda, mas os diagramas estão aí

**Comment by DanielViniciusAlves** [comment]
@SwampTG  acho interessante adicionar um ponto para manter o interesse do usuário de sempre atualizar a plataforma com sugestões de melhorias etc. Fora isso acho que está muito bom!
