### ISSUE TITLE
Priorização MoSCoW

### ISSUE THREAD

**Issue by luis-gustavo** [UnBArqDsw2022-1/2022_1_grupo5#30]
### Summary

Priorizar os requisitos elicitar por meio dá técnica MoSCoW

### Motivation

Os requisitos elicitados devem ser priorizados de modo a saber quais destes são essenciais ou não ao projeto. E quais devem ser realizados primeiro

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SwampTG** [comment]
Artefato iniciado e suficiente para a entrega https://github.com/UnBArqDsw2022-1/2022_1_grupo5/pull/32
