### ISSUE TITLE
[sketch] Rich Picture

### ISSUE THREAD

**Issue by SwampTG** [UnBArqDsw2022-1/2022_1_grupo5#7]
### Summary

Cada membro deve esboçar um Rich Picture para expormos ideias. As ideias serão unificadas em tempo futuro.
- [x] Unificar os sketches em um único.

### Motivation

Visualizar melhor o tema, atores e nuances. Conseguir que todos expressem suas opiniões e ideias.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luis-gustavo** [comment]
![Luis-RP](https://user-images.githubusercontent.com/15164988/174883215-dc8561be-e3dd-477d-a463-319aa5b930b4.png)

**Comment by LucasGlopes** [comment]
![20220620_210945](https://user-images.githubusercontent.com/49499946/174885352-f8d2e0a5-424c-4aff-a436-3d85a6215276.jpg)

**Comment by fernando-RA** [comment]
![image](https://user-images.githubusercontent.com/16293264/174897652-01828961-67d2-4bfa-9054-be1226020f93.jpeg)

**Comment by DanielViniciusAlves** [comment]
![WhatsApp Image 2022-06-21 at 19 32 22](https://user-images.githubusercontent.com/52768341/174917297-5c6ab6f9-9684-40b5-8181-1f5170664abd.jpeg)

**Comment by SwampTG** [comment]
![photo5010760984024951385](https://user-images.githubusercontent.com/66492055/174926455-ce4497f7-a2fc-42a7-97f1-eef49ab36e02.jpg)

**Comment by wesleysantos00** [comment]
![photo_2022-06-20_18-02-14](https://user-images.githubusercontent.com/54296715/175067212-565d7a53-30d6-491c-8e05-ee49ef6b0a6e.jpg)

**Comment by gpersijn** [comment]
![cel-foto](https://user-images.githubusercontent.com/56366957/175195067-edc149a0-622d-47e0-b0e8-738f5239b768.jpeg)
